title: 何文强 ｜ AI Evangelist
description: 聚焦AI技术落地，重构商业与个人工作流。
  致力于让技术走下神坛，带你用AI实现生产力跃升，打造属于你的超级个体。
  不卖焦虑，只做最接地气的AI知识传播者。
theme: jekyll-theme-slate
show_downloads: false
url: https://github.hewenqiang.com
